// Code generated from the UN Statistics Division's M49 standard
// (https://unstats.un.org/unsd/methodology/m49/overview/, fetched 2026-09-24),
// plus TW and XK, which M49 leaves out; DO NOT EDIT by hand.

package exits

// countries maps ISO 3166-1 alpha-2 codes to their UN M49 name and regions.
// Region, sub-region and intermediate region are slugs as used in
// "continent:" and "area:" locations.
var countries = map[string]country{
	"AD": {name: "Andorra", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"AE": {name: "United Arab Emirates", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"AF": {name: "Afghanistan", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"AG": {name: "Antigua and Barbuda", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"AI": {name: "Anguilla", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"AL": {name: "Albania", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"AM": {name: "Armenia", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"AO": {name: "Angola", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"AQ": {name: "Antarctica", continent: "", subRegion: "", intermediateRegion: ""},
	"AR": {name: "Argentina", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"AS": {name: "American Samoa", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"AT": {name: "Austria", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"AU": {name: "Australia", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"AW": {name: "Aruba", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"AX": {name: "\u00c5land Islands", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"AZ": {name: "Azerbaijan", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"BA": {name: "Bosnia and Herzegovina", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"BB": {name: "Barbados", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"BD": {name: "Bangladesh", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"BE": {name: "Belgium", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"BF": {name: "Burkina Faso", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"BG": {name: "Bulgaria", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"BH": {name: "Bahrain", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"BI": {name: "Burundi", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"BJ": {name: "Benin", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"BL": {name: "Saint Barth\u00e9lemy", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"BM": {name: "Bermuda", continent: "americas", subRegion: "northern-america", intermediateRegion: ""},
	"BN": {name: "Brunei Darussalam", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"BO": {name: "Bolivia (Plurinational State of)", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"BQ": {name: "Bonaire, Sint Eustatius and Saba", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"BR": {name: "Brazil", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"BS": {name: "Bahamas", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"BT": {name: "Bhutan", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"BV": {name: "Bouvet Island", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"BW": {name: "Botswana", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "southern-africa"},
	"BY": {name: "Belarus", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"BZ": {name: "Belize", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"CA": {name: "Canada", continent: "americas", subRegion: "northern-america", intermediateRegion: ""},
	"CC": {name: "Cocos (Keeling) Islands", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"CD": {name: "Democratic Republic of the Congo", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"CF": {name: "Central African Republic", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"CG": {name: "Congo", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"CH": {name: "Switzerland", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"CI": {name: "C\u00f4te d\u2019Ivoire", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"CK": {name: "Cook Islands", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"CL": {name: "Chile", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"CM": {name: "Cameroon", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"CN": {name: "China", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"CO": {name: "Colombia", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"CR": {name: "Costa Rica", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"CU": {name: "Cuba", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"CV": {name: "Cabo Verde", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"CW": {name: "Cura\u00e7ao", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"CX": {name: "Christmas Island", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"CY": {name: "Cyprus", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"CZ": {name: "Czechia", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"DE": {name: "Germany", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"DJ": {name: "Djibouti", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"DK": {name: "Denmark", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"DM": {name: "Dominica", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"DO": {name: "Dominican Republic", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"DZ": {name: "Algeria", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"EC": {name: "Ecuador", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"EE": {name: "Estonia", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"EG": {name: "Egypt", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"EH": {name: "Western Sahara", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"ER": {name: "Eritrea", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"ES": {name: "Spain", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"ET": {name: "Ethiopia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"FI": {name: "Finland", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"FJ": {name: "Fiji", continent: "oceania", subRegion: "melanesia", intermediateRegion: ""},
	"FK": {name: "Falkland Islands (Malvinas)", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"FM": {name: "Micronesia (Federated States of)", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"FO": {name: "Faroe Islands", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"FR": {name: "France", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"GA": {name: "Gabon", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"GB": {name: "United Kingdom of Great Britain and Northern Ireland", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"GD": {name: "Grenada", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"GE": {name: "Georgia", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"GF": {name: "French Guiana", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"GG": {name: "Guernsey", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"GH": {name: "Ghana", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"GI": {name: "Gibraltar", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"GL": {name: "Greenland", continent: "americas", subRegion: "northern-america", intermediateRegion: ""},
	"GM": {name: "Gambia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"GN": {name: "Guinea", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"GP": {name: "Guadeloupe", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"GQ": {name: "Equatorial Guinea", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"GR": {name: "Greece", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"GS": {name: "South Georgia and the South Sandwich Islands", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"GT": {name: "Guatemala", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"GU": {name: "Guam", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"GW": {name: "Guinea-Bissau", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"GY": {name: "Guyana", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"HK": {name: "China, Hong Kong Special Administrative Region", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"HM": {name: "Heard Island and McDonald Islands", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"HN": {name: "Honduras", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"HR": {name: "Croatia", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"HT": {name: "Haiti", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"HU": {name: "Hungary", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"ID": {name: "Indonesia", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"IE": {name: "Ireland", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"IL": {name: "Israel", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"IM": {name: "Isle of Man", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"IN": {name: "India", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"IO": {name: "British Indian Ocean Territory", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"IQ": {name: "Iraq", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"IR": {name: "Iran (Islamic Republic of)", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"IS": {name: "Iceland", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"IT": {name: "Italy", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"JE": {name: "Jersey", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"JM": {name: "Jamaica", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"JO": {name: "Jordan", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"JP": {name: "Japan", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"KE": {name: "Kenya", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"KG": {name: "Kyrgyzstan", continent: "asia", subRegion: "central-asia", intermediateRegion: ""},
	"KH": {name: "Cambodia", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"KI": {name: "Kiribati", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"KM": {name: "Comoros", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"KN": {name: "Saint Kitts and Nevis", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"KP": {name: "Democratic People's Republic of Korea", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"KR": {name: "Republic of Korea", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"KW": {name: "Kuwait", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"KY": {name: "Cayman Islands", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"KZ": {name: "Kazakhstan", continent: "asia", subRegion: "central-asia", intermediateRegion: ""},
	"LA": {name: "Lao People's Democratic Republic", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"LB": {name: "Lebanon", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"LC": {name: "Saint Lucia", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"LI": {name: "Liechtenstein", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"LK": {name: "Sri Lanka", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"LR": {name: "Liberia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"LS": {name: "Lesotho", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "southern-africa"},
	"LT": {name: "Lithuania", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"LU": {name: "Luxembourg", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"LV": {name: "Latvia", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"LY": {name: "Libya", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"MA": {name: "Morocco", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"MC": {name: "Monaco", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"MD": {name: "Republic of Moldova", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"ME": {name: "Montenegro", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"MF": {name: "Saint Martin (French Part)", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"MG": {name: "Madagascar", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"MH": {name: "Marshall Islands", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"MK": {name: "North Macedonia", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"ML": {name: "Mali", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"MM": {name: "Myanmar", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"MN": {name: "Mongolia", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"MO": {name: "China, Macao Special Administrative Region", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"MP": {name: "Northern Mariana Islands", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"MQ": {name: "Martinique", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"MR": {name: "Mauritania", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"MS": {name: "Montserrat", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"MT": {name: "Malta", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"MU": {name: "Mauritius", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"MV": {name: "Maldives", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"MW": {name: "Malawi", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"MX": {name: "Mexico", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"MY": {name: "Malaysia", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"MZ": {name: "Mozambique", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"NA": {name: "Namibia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "southern-africa"},
	"NC": {name: "New Caledonia", continent: "oceania", subRegion: "melanesia", intermediateRegion: ""},
	"NE": {name: "Niger", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"NF": {name: "Norfolk Island", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"NG": {name: "Nigeria", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"NI": {name: "Nicaragua", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"NL": {name: "Netherlands (Kingdom of the)", continent: "europe", subRegion: "western-europe", intermediateRegion: ""},
	"NO": {name: "Norway", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"NP": {name: "Nepal", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"NR": {name: "Naoero", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"NU": {name: "Niue", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"NZ": {name: "New Zealand", continent: "oceania", subRegion: "australia-and-new-zealand", intermediateRegion: ""},
	"OM": {name: "Oman", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"PA": {name: "Panama", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"PE": {name: "Peru", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"PF": {name: "French Polynesia", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"PG": {name: "Papua New Guinea", continent: "oceania", subRegion: "melanesia", intermediateRegion: ""},
	"PH": {name: "Philippines", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"PK": {name: "Pakistan", continent: "asia", subRegion: "southern-asia", intermediateRegion: ""},
	"PL": {name: "Poland", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"PM": {name: "Saint Pierre and Miquelon", continent: "americas", subRegion: "northern-america", intermediateRegion: ""},
	"PN": {name: "Pitcairn", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"PR": {name: "Puerto Rico", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"PS": {name: "State of Palestine", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"PT": {name: "Portugal", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"PW": {name: "Palau", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"PY": {name: "Paraguay", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"QA": {name: "Qatar", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"RE": {name: "R\u00e9union", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"RO": {name: "Romania", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"RS": {name: "Serbia", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"RU": {name: "Russian Federation", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"RW": {name: "Rwanda", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"SA": {name: "Saudi Arabia", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"SB": {name: "Solomon Islands", continent: "oceania", subRegion: "melanesia", intermediateRegion: ""},
	"SC": {name: "Seychelles", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"SD": {name: "Sudan", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"SE": {name: "Sweden", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"SG": {name: "Singapore", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"SH": {name: "Saint Helena", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"SI": {name: "Slovenia", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"SJ": {name: "Svalbard and Jan Mayen Islands", continent: "europe", subRegion: "northern-europe", intermediateRegion: ""},
	"SK": {name: "Slovakia", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"SL": {name: "Sierra Leone", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"SM": {name: "San Marino", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"SN": {name: "Senegal", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"SO": {name: "Somalia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"SR": {name: "Suriname", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"SS": {name: "South Sudan", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"ST": {name: "Sao Tome and Principe", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"SV": {name: "El Salvador", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "central-america"},
	"SX": {name: "Sint Maarten (Dutch part)", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"SY": {name: "Syrian Arab Republic", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"SZ": {name: "Eswatini", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "southern-africa"},
	"TC": {name: "Turks and Caicos Islands", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"TD": {name: "Chad", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "middle-africa"},
	"TF": {name: "French Southern Territories", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"TG": {name: "Togo", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "western-africa"},
	"TH": {name: "Thailand", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"TJ": {name: "Tajikistan", continent: "asia", subRegion: "central-asia", intermediateRegion: ""},
	"TK": {name: "Tokelau", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"TL": {name: "Timor-Leste", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"TM": {name: "Turkmenistan", continent: "asia", subRegion: "central-asia", intermediateRegion: ""},
	"TN": {name: "Tunisia", continent: "africa", subRegion: "northern-africa", intermediateRegion: ""},
	"TO": {name: "Tonga", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"TR": {name: "T\u00fcrkiye", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"TT": {name: "Trinidad and Tobago", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"TV": {name: "Tuvalu", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"TW": {name: "Taiwan", continent: "asia", subRegion: "eastern-asia", intermediateRegion: ""},
	"TZ": {name: "United Republic of Tanzania", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"UA": {name: "Ukraine", continent: "europe", subRegion: "eastern-europe", intermediateRegion: ""},
	"UG": {name: "Uganda", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"UM": {name: "United States Minor Outlying Islands", continent: "oceania", subRegion: "micronesia", intermediateRegion: ""},
	"US": {name: "United States of America", continent: "americas", subRegion: "northern-america", intermediateRegion: ""},
	"UY": {name: "Uruguay", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"UZ": {name: "Uzbekistan", continent: "asia", subRegion: "central-asia", intermediateRegion: ""},
	"VA": {name: "Holy See", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"VC": {name: "Saint Vincent and the Grenadines", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"VE": {name: "Venezuela (Bolivarian Republic of)", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "south-america"},
	"VG": {name: "British Virgin Islands", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"VI": {name: "United States Virgin Islands", continent: "americas", subRegion: "latin-america-and-the-caribbean", intermediateRegion: "caribbean"},
	"VN": {name: "Viet Nam", continent: "asia", subRegion: "south-eastern-asia", intermediateRegion: ""},
	"VU": {name: "Vanuatu", continent: "oceania", subRegion: "melanesia", intermediateRegion: ""},
	"WF": {name: "Wallis and Futuna Islands", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"WS": {name: "Samoa", continent: "oceania", subRegion: "polynesia", intermediateRegion: ""},
	"XK": {name: "Kosovo", continent: "europe", subRegion: "southern-europe", intermediateRegion: ""},
	"YE": {name: "Yemen", continent: "asia", subRegion: "western-asia", intermediateRegion: ""},
	"YT": {name: "Mayotte", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"ZA": {name: "South Africa", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "southern-africa"},
	"ZM": {name: "Zambia", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
	"ZW": {name: "Zimbabwe", continent: "africa", subRegion: "sub-saharan-africa", intermediateRegion: "eastern-africa"},
}
