package rss

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

const solsteinFeedURL = "https://solstein.example.com/api/feeds/abc.xml?sig=xyz"

func TestRewriteWithoutChangesIsByteIdentical(t *testing.T) {
	data := readFixture(t, "show.xml")

	output, err := Rewrite{}.Apply(data)
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !bytes.Equal(output, data) {
		t.Errorf("output differs from input with no changes requested:\n%s", output)
	}

	// Changes that match what's already there are no-ops too.
	output, err = Rewrite{Item: func(item Item) ItemChange {
		if item.Enclosure == nil {
			return ItemChange{}
		}
		return ItemChange{EnclosureURL: item.Enclosure.URL}
	}}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(output, data) {
		t.Error("replacing URLs with themselves changed the output")
	}
}

// solsteinURL maps an item to the URL Solstein would serve it at.
func solsteinURL(item Item) string {
	return "https://solstein.example.com/api/episodes/feed/" + item.Key + ".mp3?sig=s&x=1"
}

func TestRewriteShow(t *testing.T) {
	data := readFixture(t, "show.xml")
	var seen []string

	output, err := Rewrite{
		FeedURL: solsteinFeedURL,
		Item: func(item Item) ItemChange {
			seen = append(seen, item.Key)
			switch item.Key {
			case "ep-3":
				return ItemChange{EnclosureURL: solsteinURL(item), Length: 39000000, Duration: "40:00"}
			case "ep-2":
				return ItemChange{Omit: true}
			case "bonus-1":
				return ItemChange{EnclosureURL: solsteinURL(item), Length: 999}
			}
			return ItemChange{}
		},
	}.Apply(data)
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	text := string(output)

	if len(seen) != 5 {
		t.Errorf("Item called for %v, want all 5 items", seen)
	}

	// Self-links point at Solstein; the hub link is left alone.
	for _, want := range []string{
		`<atom:link href="https://solstein.example.com/api/feeds/abc.xml?sig=xyz" rel="self" type="application/rss+xml"/>`,
		`<itunes:new-feed-url>https://solstein.example.com/api/feeds/abc.xml?sig=xyz</itunes:new-feed-url>`,
		`<atom:link href="https://pubsubhubbub.appspot.com/" rel="hub"/>`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("output lacks %s", want)
		}
	}

	// Every reference to the original ep-3 audio is gone, including in
	// <media:content> and <podcast:source>, with the new length and duration.
	if strings.Contains(text, "media.example.com/ep3.mp3") {
		t.Error("original ep-3 audio URL still in output")
	}
	for _, want := range []string{
		`<enclosure url="https://solstein.example.com/api/episodes/feed/ep-3.mp3?sig=s&amp;x=1" length="39000000" type="audio/mpeg"/>`,
		`<media:content url="https://solstein.example.com/api/episodes/feed/ep-3.mp3?sig=s&amp;x=1" type="audio/mpeg" fileSize="39000000"/>`,
		`<podcast:source uri="https://solstein.example.com/api/episodes/feed/ep-3.mp3?sig=s&amp;x=1"/>`,
		`<itunes:duration>40:00</itunes:duration>`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("output lacks %s", want)
		}
	}

	// Omitted item is gone without leaving a blank line.
	if strings.Contains(text, "ep-2") || strings.Contains(text, "Episode 2") {
		t.Error("omitted item still in output")
	}
	if strings.Contains(text, "</item>\n    \n") || strings.Contains(text, "</item>\n\n") {
		t.Error("omitted item left a blank line")
	}

	// media:content-only item: its audio URL and size replaced, the image
	// untouched.
	if !strings.Contains(text, `<media:content url="https://solstein.example.com/api/episodes/feed/bonus-1.mp3?sig=s&amp;x=1" type="audio/mp4" fileSize="999"/>`) {
		t.Error("bonus media:content not rewritten as expected")
	}
	if !strings.Contains(text, `<media:content url="https://media.example.com/bonus.jpg" type="image/jpeg"/>`) {
		t.Error("image media:content was changed")
	}

	// Untouched parts are byte-identical: CDATA, entities, comments, GUIDs.
	for _, want := range []string{
		`<description><![CDATA[<p>A made-up show for <b>testing</b> & nothing else.</p>]]></description>`,
		`<title>Episode 3: The third&nbsp;one</title>`,
		`<content:encoded><![CDATA[<p>Show notes with <a href="https://example.com/?a=1&b=2">a link</a>.</p>]]></content:encoded>`,
		`<!-- generated by an example host -->`,
		`<guid isPermaLink="false">ep-3</guid>`,
		`<enclosure url="https://media.example.com/ep1.mp3" type="audio/mpeg"/>`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("output lacks unchanged %s", want)
		}
	}

	// The result is still a valid feed with the expected items.
	reparsed, err := Parse(output)
	if err != nil {
		t.Fatalf("output doesn't parse: %v", err)
	}
	var keys []string
	for _, item := range reparsed.Items {
		keys = append(keys, item.Key)
	}
	if strings.Join(keys, ",") != "ep-3,https://media.example.com/ep1.mp3,bonus-1,text-1" {
		t.Errorf("items after rewrite = %v", keys)
	}
	if reparsed.Items[0].Enclosure.Length != 39000000 || reparsed.Items[0].Duration != "40:00" {
		t.Errorf("rewritten item = %+v", reparsed.Items[0])
	}
}

func TestRewriteAddsMissingLength(t *testing.T) {
	data := readFixture(t, "show.xml")
	output, err := Rewrite{Item: func(item Item) ItemChange {
		if item.GUID == "" && item.Enclosure != nil {
			return ItemChange{Length: 5000}
		}
		return ItemChange{}
	}}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(output), `<enclosure url="https://media.example.com/ep1.mp3" type="audio/mpeg" length="5000"/>`) {
		t.Errorf("length not added:\n%s", output)
	}
}

func TestRewriteSelfClosingDuration(t *testing.T) {
	data := []byte(`<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"><channel><item><guid>a</guid><itunes:duration/><enclosure url="u" type="audio/mpeg"/></item></channel></rss>`)
	output, err := Rewrite{Item: func(Item) ItemChange { return ItemChange{Duration: "1:00"} }}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(output), `<itunes:duration>1:00</itunes:duration>`) {
		t.Errorf("output = %s", output)
	}
}

func TestRewriteOtherItunesPrefix(t *testing.T) {
	// Matching is by namespace, so a feed using another prefix still works,
	// and the prefix is kept as written.
	data := []byte(`<rss xmlns:it="http://www.itunes.com/dtds/podcast-1.0.dtd"><channel><it:new-feed-url>old</it:new-feed-url></channel></rss>`)
	output, err := Rewrite{FeedURL: "new"}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if string(output) != `<rss xmlns:it="http://www.itunes.com/dtds/podcast-1.0.dtd"><channel><it:new-feed-url>new</it:new-feed-url></channel></rss>` {
		t.Errorf("output = %s", output)
	}
}

func TestRewriteIgnoresItemLevelSelfLink(t *testing.T) {
	data := []byte(`<rss xmlns:atom="http://www.w3.org/2005/Atom"><channel><item><atom:link rel="self" href="item-link"/></item></channel></rss>`)
	output, err := Rewrite{FeedURL: "new"}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(output, data) {
		t.Errorf("item-level atom:link changed: %s", output)
	}
}

func TestRewriteLatin1(t *testing.T) {
	output, err := Rewrite{}.Apply(readFixture(t, "latin1.xml"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(output)
	if !strings.HasPrefix(text, `<?xml version="1.0" encoding="UTF-8"?>`) {
		t.Errorf("declaration not updated: %s", text[:60])
	}
	if !strings.Contains(text, "Blåbærsyltetøy") {
		t.Errorf("text not converted to UTF-8: %s", text)
	}
}

func TestRewriteInvalidFeed(t *testing.T) {
	if _, err := (Rewrite{}).Apply([]byte(`<html></html>`)); err == nil {
		t.Error("expected an error for a non-RSS document")
	}
}

func TestFormatDuration(t *testing.T) {
	cases := []struct {
		duration time.Duration
		want     string
	}{
		{0, "0:00"},
		{59 * time.Second, "0:59"},
		{42*time.Minute + 10*time.Second, "42:10"},
		{time.Hour, "1:00:00"},
		{2*time.Hour + 3*time.Minute + 4*time.Second + 600*time.Millisecond, "2:03:05"},
		{-time.Second, "0:00"},
	}
	for _, c := range cases {
		if got := FormatDuration(c.duration); got != c.want {
			t.Errorf("FormatDuration(%v) = %q, want %q", c.duration, got, c.want)
		}
	}
}

func TestRewritePubDate(t *testing.T) {
	data := readFixture(t, "show.xml")
	released := time.Date(2026, 9, 24, 10, 50, 0, 0, time.FixedZone("CEST", 2*3600))
	output, err := Rewrite{Item: func(item Item) ItemChange {
		if item.GUID == "ep-3" {
			return ItemChange{PublishedAt: &released}
		}
		return ItemChange{}
	}}.Apply(data)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(output), "<pubDate>Thu, 24 Sep 2026 08:50:00 +0000</pubDate>") {
		t.Errorf("pubDate not rewritten in UTC:\n%s", output)
	}
	if !strings.Contains(string(output), "<pubDate>Mon, 21 Sep 2026 06:00:00 +0200</pubDate>") {
		t.Error("other items' pubDate changed")
	}
	reparsed, _ := Parse(output)
	if !reparsed.Items[0].PublishedAt.Equal(released) {
		t.Errorf("reparsed date = %v", reparsed.Items[0].PublishedAt)
	}
}
